### PR TITLE
Ratelimiter middleware

### PR DESCRIPTION
**Pull request by va3y**
Addresses #62

### CODE REVIEW

**Comment by OrJDev** [comment]
we just launched a new package called prpc,
will have to see how can we link create jd app with that

https://github.com/orjdev/prpc

thank you for that

**Comment by OrJDev** [comment]
> we just launched a new package called prpc, will have to see how can we link create jd app with that
> 
> https://github.com/orjdev/prpc
> 
> thank you for that

we just added this as an addon, feel free to take a look at it and see if you could merge it with what you do

**Comment by OrJDev** [comment]
updating you we just implemented middlewares for prpc,
https://prpc.vercel.app/middleware

do you want to do that or should i?

**Comment by va3y** [comment]
Hi! Sorry, was busy with my work. 

Yea, let me go for it, the API seems pretty straightforward

**Comment by OrJDev** [comment]
> Hi! Sorry, was busy with my work.
> 
> Yea, let me go for it, the API seems pretty straightforward

alright cool lmk if you face any issue, also make sure to bump all prpc packages to latest version to get middleware to work

**Comment by va3y** [comment]
Hi again, I've added the `middleware$` boilerplate file, please take a look if I got it right :) 

I'm not sure what would be the theoretical way to handle this error in a real app. Right now, it's throwing a `new PRPCClientError`, the server handler fails and the client is getting the error as 500. Is there a way to early-return the response in `middleware$`? With that we can give the `statusCode: 429` and give some more info for the client. 

I think for boilerplate its fine as is now. Just something I couldn't get right with the pRPC. 
Still, personally I think the prpc API is much more friendly for solid-start setup. Gl with the lib progress!

**Comment by OrJDev** [comment]
> Hi again, I've added the `middleware$` boilerplate file, please take a look if I got it right :) 
> 
> 
> 
> I'm not sure what would be the theoretical way to handle this error in a real app. Right now, it's throwing a `new PRPCClientError`, the server handler fails and the client is getting the error as 500. Is there a way to early-return the response in `middleware$`? With that we can give the `statusCode: 429` and give some more info for the client. 
> 
> 
> 
> I think for boilerplate its fine as is now. Just something I couldn't get right with the pRPC. 
> 
> Still, personally I think the prpc API is much more friendly for solid-start setup. Gl with the lib progress! 
> 
> 
> 
> 
> 
> 
> 
> 

Oh prpcclienterror is not an actual thing it is just something i tried, you should throw a ServerError coming from solid start.

**Comment by va3y** [comment]
Ah alright, changed to ServerError

**Pull request merged**
