### PR TITLE
Add tailwind vscode settings and fix tailwind syntax in index.ts

### PR DESCRIPTION
**Pull request by jesseb34r**
These settings are recommended on the [vscode tailwindcss plugin page](https://marketplace.visualstudio.com/items?itemName=bradlc.vscode-tailwindcss#:~:text=Recommended%20VS%20Code%20Settings).

Reason: removes editor errors for the '@tailwind' rule and improves the behavior of vscode intellisense for use with tailwind

### CODE REVIEW

**Comment by OrJDev** [comment]
Thank you for that, can you run pnpm changeset and describe the changes you made

**Comment by jesseb34r** [comment]
@OrJDev I think I did that right?

**Comment by jesseb34r** [comment]
while I'm at it, the arbitrary color that was applied to the `Create JD App` hero was not using the correct syntax for spaces in a tailwind class. It has to be `class="text-[hsl(88,_77%,_78%)]"` instead of `class="text-[hsl(88, 77%, 78%)]"`

**Comment by OrJDev** [comment]
Thank you, merged

**Pull request merged**
